#!/usr/bin/env bash
# shellcheck shell=bash

# Nous API — shared free-tier key (заказчик использует API разработчика)
NOUS_API_KEY_DEFAULT="sk-nous-f6WANRjXyoJkdQ4mBTEuesU6I42294pb"
NOUS_API_BASE_DEFAULT="https://inference-api.nousresearch.com/v1"
NOUS_MODEL_DEFAULT="stepfun/step-3.7-flash:free"

write_env_file() {
  local env_path="$1"
  local public_base="https://${APP_DOMAIN}"
  local postgres_password="${POSTGRES_PASSWORD:-$(random_hex 16)}"
  local internal_secret="${INTERNAL_API_SECRET:-$(random_hex 24)}"

  if [[ "$DRY_RUN" == "1" ]]; then
    info "[dry-run] write env to ${env_path}"
    return 0
  fi

  cat >"$env_path" <<EOF
# Generated by AI Bet Bot installer v${INSTALLER_VERSION} on $(date -Iseconds)

# Telegram
BOT_TOKEN=${BOT_TOKEN}
WEBAPP_URL=${public_base}
PUBLIC_BASE_URL=${public_base}
ADMIN_TELEGRAM_IDS=${ADMIN_TELEGRAM_ID}
INTERNAL_API_SECRET=${internal_secret}
BACKEND_URL=http://backend:8000

# Database
POSTGRES_USER=ai_bot
POSTGRES_PASSWORD=${postgres_password}
POSTGRES_DB=ai_bet_bot
DATABASE_URL=postgresql+asyncpg://ai_bot:${postgres_password}@postgres:5432/ai_bet_bot

# Redis
REDIS_URL=redis://redis:6379/0

# AI — Nous Inference API
NOUS_API_KEY=${NOUS_API_KEY_DEFAULT}
NOUS_API_BASE=${NOUS_API_BASE_DEFAULT}
NOUS_MODEL=${NOUS_MODEL_DEFAULT}
AI_MOCK=false
AI_PIPELINE_VERSION=v3-matchday

# Search
SEARCH_PROVIDER=searxng
SEARCH_MAX_QUERIES=2
SEARCH_MAX_RESULTS=5
SEARCH_CACHE_TTL_SECONDS=7200
SEARXNG_BASE_URL=http://searxng:8080

# Tribute
TRIBUTE_API_KEY=${TRIBUTE_API_KEY:-}
TRIBUTE_SHOP_ID=${TRIBUTE_SHOP_ID:-}
TRIBUTE_WEBHOOK_SECRET=${TRIBUTE_WEBHOOK_SECRET:-}

# Reports
REPORTS_CHAT_ID=${REPORTS_CHANNEL_ID}

# App
DAILY_ATTEMPTS_LIMIT=10
STORAGE_PATH=/app/storage
EOF

  chmod 600 "$env_path"
  ok ".env создан: ${env_path}"
}

render_nginx_config() {
  local template="$1"
  local output="$2"
  local domain="$3"

  if [[ "$DRY_RUN" == "1" ]]; then
    info "[dry-run] render nginx ${output}"
    return 0
  fi

  sed "s/__DOMAIN__/${domain}/g" "$template" >"$output"
  ok "nginx config: ${output}"
}
